symbols: [BTCUSDT, ETHUSDT]
intervals: [1m, 5m, 15m]
horizons_min: [5, 15, 60]
costs:
  fee_bp: 7
  slip_k:
    low: 0.2
    med: 0.4
    high: 0.8
spread_model: median
execution:
  latency_bars: 1
  partial_fill: true
validation:
  folds: 5
  embargo_bars: 60
  min_train_bars: 50000
policy:
  prob_delta_quantile: 0.6
  prob_ema_alpha: 0.2
  min_hold_bars: 3
sizing:
  kelly_clip: 0.5
rules_path: configs/rules.yaml
