meta:
  version: 1
  description: Базовые фильтры и позиционирование

filters:
  - name: avoid_high_impact_news
    type: text_rag_any
    query: "высоковолатильные события ближайшие 30 минут"
    action: block_entries

  - name: trend_filter
    type: metric
    expr: "ema_50 > ema_200"
    action: allow_long_only

thresholds:
  - name: confidence_gate
    long_if_prob_gt: 0.62
    short_if_prob_lt: 0.38

position_sizing:
  - name: vol_scaled
    expr: "size = base_risk / max(vol_30, 1e-4)"

risk_guards:
  - name: daily_loss_stop
    type: pnl
    expr: "daily_drawdown <= 0.03"
    action: disable_trading_else

exits:
  - name: tp_sl
    take_profit: 0.01
    stop_loss: 0.005
