data:
  symbol: BTCUSDT
  interval: 1m
  window: 300
  horizon_min: 15
  lookback_days: 30
  fee_bp: 7
  slippage_bp: 5
  stream_tick_fraction: 0.0833333333333
  stream_tick_min_seconds: 1
  stream_tick_max_seconds: 15
  market_fetch_fraction: 0.25
  market_fetch_min_seconds: 1
  market_fetch_max_seconds: 15
  candles_store_path: data/live/candles.sqlite
model:
  kind: xgb
  xgb:
    max_depth: 5
    n_estimators: 500
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
  tcn:
    channels: [64, 64, 64]
    dropout: 0.1
    lr: 0.001
policy:
  conf_up: 0.6
  conf_down: 0.4
  allow_short: true
risk:
  risk_per_trade: 0.01
  daily_loss_limit: 0.03
  take_profit: 0.01
  stop_loss: 0.005
memory:
  faiss_dim_text: 384
  faiss_dim_image: 512
  text_model: all-MiniLM-L6-v2
  allowed_text_models:
    - all-MiniLM-L6-v2
    - all-MiniLM-L12-v2
    - paraphrase-MiniLM-L6-v2
auto:
  min_bars_for_train: 5000
  retrain_cooldown_min: 15
  target_atr_period: 14
  fib_entry: [0.236, 0.382]
ui:
  candle_colors:
    up_real: "#FFFFFF"
    down_real: "#000000"
    up_pred: "#00C853"
    down_pred: "#D50000"
